
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author rudolfs
 */
public class addTaskView extends javax.swing.JFrame {

    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form addTaskView
     */
    public addTaskView() {
        initComponents();
        getContentPane().setBackground(Color.gray);
        setResizable(false);
        this.setTitle("Jauns uzdevums");
        
        conn = toDoJFrame.ConnectDb();
    }

    public static Connection ConnectDb(){
        try{
            Class.forName("org.sqlite.JDBC");
            Connection conn = DriverManager.getConnection("jdbc:sqlite:toDoSQL.db");
            return conn;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        uzdNosaukums = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        uzdApraksts = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        pogaAtcelt = new javax.swing.JButton();
        pogaSaglabat = new javax.swing.JButton();
        prioritateIevade = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        datumaIevade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Uzdevuma nosaukums");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        uzdNosaukums.setColumns(20);
        uzdNosaukums.setRows(5);
        uzdNosaukums.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uzdNosaukumsKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(uzdNosaukums);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 142, -1));

        jLabel3.setText("Apraksts");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 11, -1, -1));

        uzdApraksts.setColumns(20);
        uzdApraksts.setRows(5);
        jScrollPane2.setViewportView(uzdApraksts);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 31, 142, -1));

        jLabel5.setText("Datums");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 11, -1, -1));

        pogaAtcelt.setText("Atcelt");
        pogaAtcelt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogaAtceltActionPerformed(evt);
            }
        });
        getContentPane().add(pogaAtcelt, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 56, 75, -1));

        pogaSaglabat.setText("Saglabāt");
        pogaSaglabat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogaSaglabatActionPerformed(evt);
            }
        });
        getContentPane().add(pogaSaglabat, new org.netbeans.lib.awtextra.AbsoluteConstraints(523, 85, -1, -1));

        prioritateIevade.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(prioritateIevade, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 31, 96, -1));

        jLabel6.setText("Prioritāte (1-5)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 11, -1, -1));

        datumaIevade.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1616621242197L), null, null, java.util.Calendar.DAY_OF_MONTH));
        datumaIevade.setFocusable(false);
        datumaIevade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                datumaIevadeKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                datumaIevadeKeyTyped(evt);
            }
        });
        getContentPane().add(datumaIevade, new org.netbeans.lib.awtextra.AbsoluteConstraints(324, 31, 160, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pogaAtceltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogaAtceltActionPerformed
        dispose();
    }//GEN-LAST:event_pogaAtceltActionPerformed

    private void pogaSaglabatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogaSaglabatActionPerformed
        String sql = "INSERT INTO toDoSQL(Uzdevums,Apraksts,Datums,Prioritāte)VALUES(?,?,?,?)";
        
        try{
            pst = conn.prepareStatement(sql);
            pst.setString(1, uzdNosaukums.getText());
            pst.setString(2, uzdApraksts.getText());
            pst.setString(3, String.valueOf(datumaIevade.getValue())); 
            pst.setString(4, String.valueOf(prioritateIevade.getValue()));
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Uzdevums pievienots");
            
            if (rs != null) rs.close();
            if (pst != null) pst.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        dispose();
        updateTable();
    }//GEN-LAST:event_pogaSaglabatActionPerformed

    private void uzdNosaukumsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uzdNosaukumsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_uzdNosaukumsKeyTyped

    private void datumaIevadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datumaIevadeKeyTyped
        evt.consume();
    }//GEN-LAST:event_datumaIevadeKeyTyped

    private void datumaIevadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_datumaIevadeKeyPressed
        evt.consume();
    }//GEN-LAST:event_datumaIevadeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addTaskView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner datumaIevade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton pogaAtcelt;
    private javax.swing.JButton pogaSaglabat;
    private javax.swing.JSpinner prioritateIevade;
    private javax.swing.JTextArea uzdApraksts;
    private javax.swing.JTextArea uzdNosaukums;
    // End of variables declaration//GEN-END:variables
}
